# Generated by Django 5.2.3 on 2025-06-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SquadPowerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("in_game_name", models.CharField(max_length=100)),
                ("hq_level", models.PositiveIntegerField()),
                ("squad_power", models.PositiveIntegerField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="squad_images/"),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
