# Generated by Django 5.2.3 on 2025-06-22 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geek", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="squadpowerentry",
            name="hq_level",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(30)]
            ),
        ),
        migrations.AlterField(
            model_name="squadpowerentry",
            name="image",
            field=models.ImageField(upload_to="squad_images/"),
        ),
        migrations.AlterField(
            model_name="squadpowerentry",
            name="squad_power",
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
