# Generated by Django 5.2.3 on 2025-06-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geek", "0002_alter_squadpowerentry_hq_level_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="squadpowerentry",
            name="image",
        ),
        migrations.AlterField(
            model_name="squadpowerentry",
            name="in_game_name",
            field=models.CharField(max_length=15),
        ),
    ]
